name: CI/CD - Medicare

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 🧾 Checkout code
      uses: actions/checkout@v3

    - name: ⚙️ Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: 📦 Restore dependencies
      run: dotnet restore SchoolMedicalServer.Api/SchoolMedicalServer.Api.csproj

    - name: 🛠 Build project
      run: dotnet build SchoolMedicalServer.Api/SchoolMedicalServer.Api.csproj --no-restore --configuration Release

    - name: ✅ Run unit tests
      run: dotnet test SchoolMedicalServer.Test/SchoolMedicalServer.Test.csproj --verbosity normal --collect:"XPlat Code Coverage" /p:ExcludeByFile="SchoolMedicalServer.Infrastructure/Migrations/*.cs"
      
    - name: 🧾 Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./SchoolMedicalServer.Test/TestResults/**/*.cobertura.xml
        fail_ci_if_error: true

    - name: 📈 Generate HTML coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:SchoolMedicalServer.Test/TestResults/**/*.cobertura.xml -targetdir:coverage-report -reporttypes:Html

    - name: 📤 Upload HTML coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html-report
        path: coverage-report

    - name: 🐳 Build Docker image
      run: docker build -t medicare-api -f SchoolMedicalServer.Api/Dockerfile .

    - name: 🐳 Run Docker Compose
      run: docker-compose -f docker-compose/docker-compose.yml up --build -d
